import type { KindnessNote } from "./types";

export const kindnessSeeds: KindnessNote[] = [
  {
    id: "seed-01",
    body: "Your unfinished sketch still stopped me in my tracks. Keep going — the world needs that color.",
    fromLabel: "Maya · studio upstairs",
    medium: "visual",
    spark: "coral",
    createdAt: "2026-07-12T18:20:00.000Z",
    source: "seed",
  },
  {
    id: "seed-02",
    body: "Heard you rehearse through the alley. That bridge in the second verse? Pure electricity.",
    fromLabel: "Anonymous artist",
    medium: "music",
    spark: "teal",
    createdAt: "2026-07-18T21:05:00.000Z",
    source: "seed",
  },
  {
    id: "seed-03",
    body: "Thank you for holding the door open for new voices at Hacienda. Kindness is a stage too.",
    fromLabel: "Jordan",
    medium: "theater",
    spark: "gold",
    createdAt: "2026-07-22T14:40:00.000Z",
    source: "seed",
  },
  {
    id: "seed-04",
    body: "To whoever left the pastel set by the window — I used the rose today. You made a stranger brave.",
    fromLabel: "Anonymous artist",
    medium: "open-heart",
    spark: "coral",
    createdAt: "2026-07-28T16:12:00.000Z",
    source: "seed",
  },
  {
    id: "seed-05",
    body: "Clematis nights feel softer when we clap for each other. See you under the lights.",
    fromLabel: "Rae",
    medium: "anyone",
    spark: "teal",
    createdAt: "2026-08-01T01:10:00.000Z",
    source: "seed",
  },
  {
    id: "seed-06",
    body: "Your mural on the side wall taught my niece that art belongs outside museums. Forever grateful.",
    fromLabel: "Parent from downtown",
    medium: "visual",
    spark: "gold",
    createdAt: "2026-08-02T19:30:00.000Z",
    source: "seed",
  },
  {
    id: "seed-07",
    body: "Missed a cue last night. The cast covered me with grace. That’s the show I want to be in.",
    fromLabel: "Ensemble",
    medium: "theater",
    spark: "coral",
    createdAt: "2026-08-03T23:45:00.000Z",
    source: "seed",
  },
  {
    id: "seed-08",
    body: "Play the song you’re scared of. Someone in the back row needs it more than you know.",
    fromLabel: "Anonymous artist",
    medium: "music",
    spark: "gold",
    createdAt: "2026-08-04T20:00:00.000Z",
    source: "seed",
  },
  {
    id: "seed-09",
    body: "Creativity needs kindness — and today you both showed up. West Palm is lucky.",
    fromLabel: "Robbie’s neighbor",
    medium: "open-heart",
    spark: "teal",
    createdAt: "2026-08-05T12:00:00.000Z",
    source: "seed",
  },
  {
    id: "seed-10",
    body: "Left a note for the next painter: the light at 4pm here is a gift. Share it.",
    fromLabel: "Visitor from Tampa",
    medium: "anyone",
    spark: "coral",
    createdAt: "2026-08-06T15:20:00.000Z",
    source: "seed",
  },
];
