import type {
  ArtistDetail,
  PostDetail,
  PostSummary,
  TagSummary,
} from "@/features/posts/types";

export const fixtureTags: TagSummary[] = [
  { id: "tag-abstract", name: "Abstract", slug: "abstract" },
  { id: "tag-3d", name: "3D", slug: "3d" },
  { id: "tag-photo", name: "Photography", slug: "photography" },
  { id: "tag-motion", name: "Motion", slug: "motion" },
  { id: "tag-collage", name: "Collage", slug: "collage" },
  { id: "tag-neon", name: "Neon", slug: "neon" },
];

const artists = {
  luna: {
    id: "artist-luna",
    handle: "lunavoss",
    name: "Luna Voss",
    bio: "Light sculptor exploring grain, glare, and late-night city hush.",
    avatarUrl:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
    socialLinks: {
      website: "https://example.com/luna",
      instagram: "https://instagram.com/lunavoss",
    },
  },
  kai: {
    id: "artist-kai",
    handle: "kaichan",
    name: "Kai Chan",
    bio: "Spatial designer building soft architectures for restless screens.",
    avatarUrl:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
    socialLinks: {
      behance: "https://behance.net/kaichan",
      twitter: "https://x.com/kaichan",
    },
  },
  mira: {
    id: "artist-mira",
    handle: "miranoir",
    name: "Mira Noir",
    bio: "Collage poet stitching archival dust into luminous sequences.",
    avatarUrl:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80",
    socialLinks: {
      website: "https://example.com/mira",
      instagram: "https://instagram.com/miranoir",
    },
  },
} as const;

const media = [
  "https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1614850715649-1d0106293bd1?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1567095761054-7a02e69e5c43?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1515405295579-ba7b45403062?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1500462918059-b1a0cb512f1d?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1604871000636-074fa5117945?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1618172193622-ae2d153f0968?auto=format&fit=crop&w=1200&q=80",
];

function pickTags(...slugs: string[]) {
  return fixtureTags.filter((t) => slugs.includes(t.slug));
}

export const fixturePosts: PostDetail[] = [
  {
    id: "post-1",
    slug: "midnight-filament",
    title: "Midnight Filament",
    description:
      "A field study of electric threads drifting through velvet air. Hover, tilt, and watch the grain wake up.",
    mediaUrl: media[0],
    mediaType: "IMAGE",
    theme: { primary: "#d6ff3f", secondary: "#0b0e14", layoutStyle: "bleed" },
    featured: false,
    viewCount: 1842,
    likeCount: 214,
    commentCount: 2,
    publishedAt: "2026-07-12T18:00:00.000Z",
    status: "PUBLISHED",
    tags: pickTags("abstract", "neon", "motion"),
    artist: artists.luna,
    comments: [
      {
        id: "c1",
        body: "The grain feels like breathing. Gorgeous restraint.",
        createdAt: "2026-07-13T10:00:00.000Z",
        author: { id: "u-kai", name: "Kai Chan", image: artists.kai.avatarUrl },
      },
      {
        id: "c2",
        body: "Want this as a loop for the lobby installation.",
        createdAt: "2026-07-14T09:20:00.000Z",
        author: {
          id: "u-mira",
          name: "Mira Noir",
          image: artists.mira.avatarUrl,
        },
      },
    ],
  },
  {
    id: "post-2",
    slug: "soft-architectures",
    title: "Soft Architectures",
    description:
      "Rooms that refuse corners. A gentle collision of fog, mesh, and overheard silence.",
    mediaUrl: media[1],
    mediaType: "IMAGE",
    theme: { primary: "#7dd3fc", secondary: "#0b0e14", layoutStyle: "framed" },
    featured: false,
    viewCount: 1320,
    likeCount: 167,
    commentCount: 1,
    publishedAt: "2026-07-18T15:00:00.000Z",
    status: "PUBLISHED",
    tags: pickTags("3d", "abstract"),
    artist: artists.kai,
    comments: [
      {
        id: "c3",
        body: "Feels like walking through a held breath.",
        createdAt: "2026-07-19T12:00:00.000Z",
        author: {
          id: "u-luna",
          name: "Luna Voss",
          image: artists.luna.avatarUrl,
        },
      },
    ],
  },
  {
    id: "post-3",
    slug: "archive-bloom",
    title: "Archive Bloom",
    description:
      "Torn paper memories reassembled into a garden that only exists at 60fps.",
    mediaUrl: media[2],
    mediaType: "IMAGE",
    theme: { primary: "#fb7185", secondary: "#0b0e14", layoutStyle: "stack" },
    featured: false,
    viewCount: 980,
    likeCount: 142,
    commentCount: 0,
    publishedAt: "2026-07-22T12:00:00.000Z",
    status: "PUBLISHED",
    tags: pickTags("collage", "photography"),
    artist: artists.mira,
    comments: [],
  },
  {
    id: "post-4",
    slug: "orbit-studies",
    title: "Orbit Studies",
    description: "Small moons practicing patience around a restless nucleus.",
    mediaUrl: media[3],
    mediaType: "CANVAS",
    theme: { primary: "#d6ff3f", layoutStyle: "orbit" },
    featured: false,
    viewCount: 2211,
    likeCount: 301,
    commentCount: 0,
    publishedAt: "2026-07-28T20:00:00.000Z",
    status: "PUBLISHED",
    tags: pickTags("3d", "motion"),
    artist: artists.luna,
    comments: [],
  },
  {
    id: "post-5",
    slug: "signal-garden",
    title: "Signal Garden",
    description: "Broadcast flora growing through cracked glass.",
    mediaUrl: media[4],
    mediaType: "IMAGE",
    theme: { layoutStyle: "bleed" },
    featured: false,
    viewCount: 640,
    likeCount: 88,
    commentCount: 0,
    publishedAt: "2026-08-01T11:00:00.000Z",
    status: "PUBLISHED",
    tags: pickTags("neon", "abstract"),
    artist: artists.kai,
    comments: [],
  },
  {
    id: "post-6",
    slug: "paper-tide",
    title: "Paper Tide",
    description: "Folded horizons that refuse to stay still.",
    mediaUrl: media[5],
    mediaType: "IMAGE",
    theme: { layoutStyle: "framed" },
    featured: false,
    viewCount: 512,
    likeCount: 73,
    commentCount: 0,
    publishedAt: "2026-08-02T16:00:00.000Z",
    status: "PUBLISHED",
    tags: pickTags("collage", "motion"),
    artist: artists.mira,
    comments: [],
  },
  {
    id: "post-7",
    slug: "chrome-lullaby",
    title: "Chrome Lullaby",
    description: "Reflections practicing kindness on cold metal.",
    mediaUrl: media[6],
    mediaType: "IMAGE",
    theme: { layoutStyle: "bleed" },
    featured: false,
    viewCount: 870,
    likeCount: 119,
    commentCount: 0,
    publishedAt: "2026-08-03T09:00:00.000Z",
    status: "PUBLISHED",
    tags: pickTags("photography", "neon"),
    artist: artists.luna,
    comments: [],
  },
  {
    id: "post-8",
    slug: "mesh-memory",
    title: "Mesh Memory",
    description: "Wireframes that remember the last color you touched.",
    mediaUrl: media[7],
    mediaType: "IMAGE",
    theme: { layoutStyle: "stack" },
    featured: false,
    viewCount: 430,
    likeCount: 61,
    commentCount: 0,
    publishedAt: "2026-08-04T14:00:00.000Z",
    status: "PUBLISHED",
    tags: pickTags("3d", "abstract"),
    artist: artists.kai,
    comments: [],
  },
  {
    id: "post-9",
    slug: "dust-chorus",
    title: "Dust Chorus",
    description: "Particles singing in a key only windows can hear.",
    mediaUrl: media[8],
    mediaType: "IMAGE",
    theme: { layoutStyle: "orbit" },
    featured: false,
    viewCount: 701,
    likeCount: 94,
    commentCount: 0,
    publishedAt: "2026-08-05T17:00:00.000Z",
    status: "PUBLISHED",
    tags: pickTags("motion", "abstract"),
    artist: artists.mira,
    comments: [],
  },
  {
    id: "post-10",
    slug: "amber-relay",
    title: "Amber Relay",
    description: "A handoff of warmth between distant frames.",
    mediaUrl: media[9],
    mediaType: "IMAGE",
    theme: { layoutStyle: "framed" },
    featured: false,
    viewCount: 390,
    likeCount: 52,
    commentCount: 0,
    publishedAt: "2026-08-05T21:00:00.000Z",
    status: "PUBLISHED",
    tags: pickTags("photography", "collage"),
    artist: artists.luna,
    comments: [],
  },
  {
    id: "post-11",
    slug: "glitch-orchard",
    title: "Glitch Orchard",
    description: "Fruit that ripens in scanlines.",
    mediaUrl: media[10],
    mediaType: "IMAGE",
    theme: { layoutStyle: "bleed" },
    featured: false,
    viewCount: 555,
    likeCount: 80,
    commentCount: 0,
    publishedAt: "2026-08-06T08:00:00.000Z",
    status: "PUBLISHED",
    tags: pickTags("neon", "collage"),
    artist: artists.kai,
    comments: [],
  },
  {
    id: "post-12",
    slug: "velvet-vector",
    title: "Velvet Vector",
    description: "Soft arrows pointing toward quieter pixels.",
    mediaUrl: media[11],
    mediaType: "IMAGE",
    theme: { layoutStyle: "stack" },
    featured: false,
    viewCount: 612,
    likeCount: 91,
    commentCount: 0,
    publishedAt: "2026-08-06T10:00:00.000Z",
    status: "PUBLISHED",
    tags: pickTags("abstract", "motion"),
    artist: artists.mira,
    comments: [],
  },
];

export function toSummary(post: PostDetail): PostSummary {
  return {
    id: post.id,
    slug: post.slug,
    title: post.title,
    description: post.description,
    mediaUrl: post.mediaUrl,
    mediaType: post.mediaType,
    theme: post.theme,
    featured: post.featured,
    viewCount: post.viewCount,
    likeCount: post.likeCount,
    commentCount: post.commentCount,
    publishedAt: post.publishedAt,
    tags: post.tags,
    artist: post.artist,
  };
}

export function getFixtureArtist(handle: string): ArtistDetail | null {
  const artist = Object.values(artists).find((a) => a.handle === handle);
  if (!artist) return null;
  return {
    ...artist,
    posts: fixturePosts
      .filter((p) => p.artist.handle === handle)
      .map(toSummary),
  };
}
